export const PASAJE_LIST_REQUEST = "PASAJE_LIST_REQUEST";
export const PASAJE_LIST_SUCCESS = "PASAJE_LIST_SUCCESS";
export const PASAJE_LIST_FAIL = "PASAJE_LIST_FAIL";

export const PASAJE_DESTINOS_REQUEST = "PASAJE_DESTINOS_REQUEST";
export const PASAJE_DESTINOS_SUCCESS = "PASAJE_DESTINOS_SUCCESS";
export const PASAJE_DESTINOS_FAIL = "PASAJE_DESTINOS_FAIL";

export const PASAJE_ORIGENES_REQUEST = "PASAJE_DESTINOS_REQUEST";
export const PASAJE_ORIGENES_SUCCESS = "PASAJE_DESTINOS_SUCCESS";
export const PASAJE_ORIGENES_FAIL = "PASAJE_DESTINOS_FAIL";
